# main text of home
name: Kevin Chen
intro: I'm a senior at the University of Pennsylvania, studying Electrical and Computer Engineering. Welcome to my page!
bio: Senior at the University of Pennsylvania, studying Electrical and Computer Engineering

# twitter summary info
description: A page about Kevin!

# if it's an external image, update below for true
# better with square images
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: false
resume-url: assets\KChen Resume 2020.1.pdf

url: https://kchen7.github.io/kevinchen

permalink: /:title/

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
# instagram: myinstagram
# pinterest: mypinterest
linkedin: kevinchen929
# youtube: myyoutube
# spotify: myspotify
github: kchen7
showgithub: false # dunno why, but website errors when github is commented out, so I added different variable
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: kchen7@seas.upenn.edu

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# what pages to display?
projects: true
about: true
# blog: true

# do you want some animations?
animation: true

####################### CUSTOMIZE POSTS #######################

# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# show author block at the end of a post ?
show-author: false

##############################################################

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false # TODO: what is this? delete?

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com

compress_html:
    ignore:
        envs:
        - development
        - stage

exclude: ["travis.sh", "README.md", "Gemfile", "Gemfile.lock", "FAQ.md", "node_modules", "vendor"]
